In [114]:
import numpy as np
import pandas as pd
import seaborn as sns

In [115]:
movies = pd.read_csv("../Data/tmdb_5000_movies.csv",low_memory=False)
credits = pd.read_csv("../Data/tmdb_5000_credits.csv",low_memory=False)

In [116]:
movies.sample(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2112,20000000,"[{""id"": 35, ""name"": ""Comedy""}]",http://stxmovies.com/badmoms/,376659,"[{""id"": 567, ""name"": ""alcohol""}, {""id"": 1010, ...",en,Bad Moms,When three overworked and under-appreciated mo...,42.512296,"[{""name"": ""STX Entertainment"", ""id"": 47729}, {...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-07-28,183936074,100.0,"[{""iso_639_1"": ""ru"", ""name"": ""P\u0443\u0441\u0...",Released,Party like a mother.,Bad Moms,6.3,1252
2425,17000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 53, ""nam...",NaN,16028,"[{""id"": 236, ""name"": ""suicide""}, {""id"": 2884, ...",en,They,After witnessing a horrific and traumatic even...,4.544216,"[{""name"": ""Dimension Films"", ""id"": 7405}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-11-01,0,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Are you afraid of the dark? You should be.,They,4.6,74
2119,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://www.tigger.com,15655,"[{""id"": 3905, ""name"": ""owl""}, {""id"": 4144, ""na...",en,The Tigger Movie,"As it happens, everybody - Pooh, Piglet, Eeyor...",9.829859,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2000-02-11,45554533,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,The Tigger Movie,6.3,143
2597,0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 35, ""nam...",NaN,10743,"[{""id"": 159607, ""name"": ""grifter""}, {""id"": 159...",en,Confidence,What Jake Vig doesn't know just might get him ...,9.874190,"[{""name"": ""Cinerenta Medienbeteiligungs KG"", ""...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2003-04-25,0,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,It's not about the money. It's about the money.,Confidence,6.4,126
4217,1500000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",NaN,9344,"[{""id"": 1525, ""name"": ""puberty""}, {""id"": 2201,...",en,Kids,A controversial portrayal of teens in New York...,13.291991,"[{""name"": ""Miramax Films"", ""id"": 14}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1995-07-28,7412216,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,Kids,6.8,279
2255,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",https://www.miramax.com/movie/the-yards,19457,"[{""id"": 417, ""name"": ""corruption""}, {""id"": 155...",en,The Yards,"In the rail yards of Queens, contractors repai...",10.150993,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2000-04-27,0,115.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He's the target of the most merciless family i...,The Yards,6.0,97
2478,16000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",NaN,25166,"[{""id"": 3301, ""name"": ""suspicion""}, {""id"": 387...",en,Drowning Mona,The recently deceased Mona Dearly (Bette Midle...,3.021835,"[{""name"": ""Code Entertainment"", ""id"": 14589}, ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2000-03-03,15427192,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The death of Mona Dearly wasn't so much a whod...,Drowning Mona,5.4,43
1505,32000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",http://www.bigmommaslikefatherlikeson.com/,38322,"[{""id"": 1568, ""name"": ""undercover""}, {""id"": 18...",en,"Big Mommas: Like Father, Like Son",FBI agent Malcolm Turner and his 17-year-old s...,15.901137,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2011-02-16,83615414,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Momma's got back-up.,"Big Mommas: Like Father, Like Son",5.3,313
3575,5000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,2295,"[{""id"": 10183, ""name"": ""independent film""}, {""...",en,Clerks II,A calamity at Dante and Randall's shops sends ...,18.077963,"[{""name"": ""The Weinstein Company"", ""id"": 308},...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2006-05-25,26888376,97.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,With No Power Comes No Responsibility,Clerks II,6.9,398
2228,20000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 14, ""nam...",http://www.americancarol.com/,13948,"[{""id"": 949, ""name"": ""terrorist""}, {""id"": 9755...",en,An American Carol,"In An American Carol a cynical, Anti-American ...",2.605374,"[{""name"": ""Mpower Pictures"", ""id"": 5294}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-10-03,7000000,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Laugh like you're country depends on it.,An American Carol,4.1,20

In [117]:
credits.sample(10)

,movie_id,title,cast,crew
383,664,Twister,"[{""cast_id"": 22, ""character"": ""Dr. Jo Harding""...","[{""credit_id"": ""52fe4266c3a36847f801b8e7"", ""de..."
927,13673,Christmas with the Kranks,"[{""cast_id"": 1, ""character"": ""Luther Krank"", ""...","[{""credit_id"": ""558fe9de92514122ae000bb4"", ""de..."
2366,848,Dragonslayer,"[{""cast_id"": 16, ""character"": ""Galen"", ""credit...","[{""credit_id"": ""52fe4281c3a36847f8024305"", ""de..."
605,59981,Legends of Oz: Dorothy's Return,"[{""cast_id"": 2, ""character"": ""Dorothy (voice)""...","[{""credit_id"": ""5502c097c3a3685b9e003f47"", ""de..."
672,1427,Perfume: The Story of a Murderer,"[{""cast_id"": 9, ""character"": ""Jean-Baptiste Gr...","[{""credit_id"": ""52fe42f6c3a36847f80300f5"", ""de..."
2948,11109,Vera Drake,"[{""cast_id"": 2, ""character"": ""Vera Drake"", ""cr...","[{""credit_id"": ""52fe43f99251416c75024b67"", ""de..."
4238,3082,Modern Times,"[{""cast_id"": 8, ""character"": ""A factory worker...","[{""credit_id"": ""5621aeadc3a3680e1d00a09a"", ""de..."
2449,4584,Sense and Sensibility,"[{""cast_id"": 6, ""character"": ""Marianne Dashwoo...","[{""credit_id"": ""52fe43cec3a36847f807101f"", ""de..."
1294,16320,Serenity,"[{""cast_id"": 3, ""character"": ""Mal"", ""credit_id...","[{""credit_id"": ""52fe46c59251416c75082fe3"", ""de..."
1047,10731,The Client,"[{""cast_id"": 11, ""character"": ""Regina \""Reggie...","[{""credit_id"": ""572e51efc3a36869e6002179"", ""de..."

In [118]:
movies.shape

(4803, 20)

In [119]:
credits.shape

(4803, 4)

In [120]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [121]:
movies.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [122]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [123]:
credits.dtypes

movie_id     int64
title       object
cast        object
crew        object
dtype: object

In [124]:
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [125]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [126]:
movies = movies.merge(credits,on='title')

In [127]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [128]:
movies.shape

(4809, 23)

In [129]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [130]:
movies.duplicated().sum()

np.int64(0)

In [131]:
movies = movies[["movie_id", "title", "overview", "genres", 
                 "keywords", "cast", "crew", "tagline",
                 "vote_average", "popularity"]]

In [132]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Enter the World of Pandora.,7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","At the end of the world, the adventure begins.",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A Plan No One Escapes,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Legend Ends,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","Lost in our world, found in another.",6.1,43.926995

In [133]:
movies.shape

(4809, 10)

In [134]:
import ast
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [135]:

movies.dropna(inplace=True)

In [136]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Enter the World of Pandora.,7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","At the end of the world, the adventure begins.",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A Plan No One Escapes,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Legend Ends,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","Lost in our world, found in another.",6.1,43.926995

In [137]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Enter the World of Pandora.,7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","At the end of the world, the adventure begins.",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A Plan No One Escapes,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Legend Ends,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","Lost in our world, found in another.",6.1,43.926995

In [139]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [140]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",Enter the World of Pandora.,7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","At the end of the world, the adventure begins.",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",A Plan No One Escapes,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",The Legend Ends,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","Lost in our world, found in another.",6.1,43.926995

In [141]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [142]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [143]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [144]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
3443,338,"Good bye, Lenin!",An affectionate and refreshing East/West-Germa...,"[Comedy, Drama, Romance]","[bureaucracy, berlin wall, police state, coma,...","[Daniel Brühl, Katrin Sass, Chulpan Khamatova]",[Wolfgang Becker],The German Democratic Republic lives on -- in ...,7.4,11.086001
1635,9920,Ultraviolet,"In the late 21st century, a subculture of huma...","[Science Fiction, Action, Thriller]","[skyscraper, vampire, victim, dystopia, boy, d...","[Milla Jovovich, Cameron Bright, Nick Chinlund]",[Kurt Wimmer],The blood war is on.,4.8,15.895340
348,8355,Ice Age: Dawn of the Dinosaurs,Times are changing for Manny the moody mammoth...,"[Animation, Comedy, Family, Adventure]","[ice age, bridge, insanity, jungle, dinosaur, ...","[Ray Romano, John Leguizamo, Denis Leary]",[Carlos Saldanha],You Won't Believe Your Ice!,6.5,69.457898
547,23629,Sucker Punch,A young girl is institutionalized by her abusi...,"[Action, Fantasy, Thriller]","[brothel, fantasy, asylum, reality, escape, ro...","[Emily Browning, Abbie Cornish, Jena Malone]",[Zack Snyder],You will be unprepared,5.9,39.127082
2422,41382,Lottery Ticket,Kevin Carson is a young man living in the proj...,[Comedy],[],"[Shad Moss, Brandon T. Jackson, Naturi Naughton]",[Erik White],Winning is Just the Beginning Surviving is Ano...,5.6,9.054803

In [145]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [146]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [147]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tagline,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],Enter the World of Pandora.,7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"At the end of the world, the adventure begins.",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],A Plan No One Escapes,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],The Legend Ends,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"Lost in our world, found in another.",6.1,43.926995

In [148]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [149]:
movies["tagline"]  = movies["tagline"].fillna("").apply(lambda x: x.split())

In [150]:
movies["tags"] = (
    movies["overview"] +
    movies["genres"] +
    movies["keywords"] +
    movies["cast"] +
    movies["crew"] +
    movies["tagline"]
)

In [151]:
movies['tags'][1]

['Captain',
 'Barbossa,',
 'long',
 'believed',
 'to',
 'be',
 'dead,',
 'has',
 'come',
 'back',
 'to',
 'life',
 'and',
 'is',
 'headed',
 'to',
 'the',
 'edge',
 'of',
 'the',
 'Earth',
 'with',
 'Will',
 'Turner',
 'and',
 'Elizabeth',
 'Swann.',
 'But',
 'nothing',
 'is',
 'quite',
 'as',
 'it',
 'seems.',
 'Adventure',
 'Fantasy',
 'Action',
 'ocean',
 'drugabuse',
 'exoticisland',
 'eastindiatradingcompany',
 "loveofone'slife",
 'traitor',
 'shipwreck',
 'strongwoman',
 'ship',
 'alliance',
 'calypso',
 'afterlife',
 'fighter',
 'pirate',
 'swashbuckler',
 'aftercreditsstinger',
 'JohnnyDepp',
 'OrlandoBloom',
 'KeiraKnightley',
 'GoreVerbinski',
 'At',
 'the',
 'end',
 'of',
 'the',
 'world,',
 'the',
 'adventure',
 'begins.']

In [152]:
movies["tags"] = movies["tags"].apply(lambda x: " ".join(x))

In [153]:
movies['tags'][1]

"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy Action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger JohnnyDepp OrlandoBloom KeiraKnightley GoreVerbinski At the end of the world, the adventure begins."

In [154]:
df = movies[["movie_id", "title", "tags", "vote_average", "popularity"]].copy()

In [155]:
df = df.dropna(subset=["tags"])

In [156]:
df = df.reset_index(drop=True)

In [157]:
df.shape

(3965, 5)

In [158]:
df.head()

,movie_id,title,tags,vote_average,popularity
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",7.2,150.437577
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",6.9,139.082615
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,6.3,107.376788
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,7.6,112.312950
4,49529,John Carter,"John Carter is a war-weary, former military ca...",6.1,43.926995

In [159]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re  #regular expression

In [160]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [161]:
stop_words=set(stopwords.words('english'))
lemmatizer= WordNetLemmatizer()

In [162]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed  punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [163]:
df['tags'] = df['tags'].apply(preprocess_text)

In [164]:
df['tags'][1]

'captain barbossa long believed dead come back life headed edge earth turner elizabeth swann nothing quite seems adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofoneslife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski end world adventure begin'

In [165]:
df=df.reset_index(drop=True)

In [166]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
Bang                                        3960
Primer                                      3961
El Mariachi                                 3962
Newlyweds                                   3963
Shanghai Calling                            3964
Length: 3965, dtype: int64

In [167]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [176]:
tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2),stop_words='english')

In [177]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [178]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 129875 stored elements and shape (3965, 5000)>

In [179]:
from sklearn.metrics.pairwise import cosine_similarity

In [180]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [181]:
recommend('Avatar',5)

2223                                        Aliens
46                         Star Trek Into Darkness
756                                      Meet Dave
525                                     Titan A.E.
360     Lara Croft Tomb Raider: The Cradle of Life
Name: title, dtype: object

In [182]:
recommend('Avenger',5)

['Movie not found']

In [183]:
import pickle

pickle.dump(tfidf_matrix, open('../models/tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('../models/indices.pkl', 'wb'))
pickle.dump(tfidf, open('../models/tfidf.pkl', 'wb'))

df.to_pickle('../models/df.pkl')

In [184]:

import os

models_dir = "../models"

for f in ["df.pkl", "indices.pkl", "tfidf_matrix.pkl", "tfidf.pkl"]:
    path = os.path.join(models_dir, f)
    size = os.path.getsize(path)
    print(f"{f}: {size / (1024*1024):.2f} MB")

df.pkl: 1.68 MB
indices.pkl: 0.12 MB
tfidf_matrix.pkl: 1.50 MB
tfidf.pkl: 0.18 MB

In [185]:
with open("../models/tfidf_matrix.pkl", "rb") as f:
    matrix = pickle.load(f)

with open("../models/df.pkl", "rb") as f:
    df = pickle.load(f)

print("Matrix shape:", matrix.shape)
print("Movies count:", len(df))
print("df columns:", df.columns.tolist())
print(df.head(2))

Matrix shape: (3965, 5000)
Movies count: 3965
df columns: ['movie_id', 'title', 'tags', 'vote_average', 'popularity']
   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End

                                                tags  vote_average  popularity
0  nd century paraplegic marine dispatched moon p...           7.2  150.437577
1  captain barbossa long believed dead come back ...           6.9  139.082615